### ISSUE TITLE
cannot find forkserver

### ISSUE THREAD

**Issue by StefanGrindelwald** [voiler/PopulationBasedTraining#1]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    mp = _mp.get_context('forkserver')
  File "D:\Software\Python\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "D:\Software\Python\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'forkserver'

**Comment by wu-yang-work** [comment]
I meet the same problem，just comment it, it will work well。this will happen in windows.
